substitutions:
_SERVICE_NAME: basic-app
_REGION: us-central1

steps:
- name: 'gcr.io/cloud-builders/docker'
args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
 args: ['push', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA']

 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
 args:
 - run
 - deploy
 - $_SERVICE_NAME
 - --image
 - gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA
 - --region
 - $_REGION
 - --platform
 - managed
 - --allow-unauthenticated
